version = 1


[[annotations]]
path = ["lua/**", "sample/**", "tests/**", "README.md", "REUSE.toml"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Arne Naegel"
SPDX-License-Identifier = "LicenseRef-UG4-LGPL-3.0"

